### ISSUE TITLE
Ouch: "Black" is not a valid background option.

### ISSUE THREAD

**Issue by peng051410** [NealST/github-cli#1]
执行gh 命令时一起出现这个错误，要怎么处理一下？

**Comment by NealST** [comment]
我去看一下，看报错应该是chalk中black color被deprecated了

在 2018-07-06 13:38:42，"tomyli" <notifications@github.com> 写道：


执行gh 命令时一起出现这个错误，要怎么处理一下？

**Comment by NealST** [comment]
hello, 我已经解决了这个问题，请重新安装一下更新到1.0.8即可，npm i -g @mozheng-neal/github_cli@1.0.8, 非常感谢您及时反馈的问题。

在 2018-07-06 13:38:42，"tomyli" <notifications@github.com> 写道：


执行gh 命令时一起出现这个错误，要怎么处理一下？

**Comment by peng051410** [comment]
可以了，但是我运行gh us ls -m报下面的错误：
![image](https://user-images.githubusercontent.com/5512326/42363717-2fdb514e-812b-11e8-8629-e7ca2e01a6f9.png)
这要怎么处理？

**Comment by peng051410** [comment]
我执行这些操作并不有出现让我输入用户名或者访问token的地方

**Comment by NealST** [comment]
sorry, 刚看到您的反馈，请升级下到1.0.9，修复一个文件读写错误

**Comment by NealST** [comment]
sorry，请升级下到1.0.9，有个文件读写返回出错了，抱歉 @peng051410

**Comment by peng051410** [comment]
可以了，谢谢！
